[package]
name = "terraspiel"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core
winit = { version = "0.30", features = ["default", "rwh_05"] }
pixels = "0.14"
serde = { version = "1.0", features = ["derive"] }
